services:
  gateway:
    build:
      context: ..
      dockerfile: DockerFiles/Prod/nginx.dockerfile
    image: gatekeeper-gateway:prod
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - frontend_dist:/usr/share/nginx/html
    networks:
      - app

  frontend:
    build:
      context: ..
      dockerfile: DockerFiles/Prod/frontend.dockerfile
    image: gatekeeper-frontend:prod
    depends_on:
      - backend
    networks:
      - app
    volumes:
      - frontend_dist:/app/dist

  backend:
    build:
      context: ..
      dockerfile: DockerFiles/Prod/backend.dockerfile
    image: gatekeeper-backend:prod
    env_file:
      - ./Env/backend.env
    networks:
      - app

volumes:
  frontend_dist:
    name: gatekeeper_frontend_dist

networks:
  app: