services:
  gateway:
    build:
      context: ..
      dockerfile: DockerFiles/Prod/nginx.dockerfile
    image: gatekeeper-gateway:prod
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - frontend_dist:/usr/share/nginx/html
    networks:
      - backend
  
  frontend:
    build:
      context: ..
      dockerfile: DockerFiles/Prod/frontend.dockerfile
    image: gatekeeper-frontend:prod
    depends_on:
      - backend
    networks:
      - backend
    volumes:
      - frontend_dist:/app/dist


  backend:
    build:
      context: ..
      dockerfile: DockerFiles/Prod/backend.dockerfile
    image: gatekeeper-backend:prod
    env_file:
      - ./Env/backend.env
    depends_on:
      - mongo
      - redis
    networks:
      - backend

  mongo:
    image: mongo:7
    env_file:
      - ./Env/mongo.env
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --aclfile /usr/local/etc/redis/users.acl
    volumes:
      - redis_data:/data
      - ../redis/users.acl:/usr/local/etc/redis/users.acl:ro
    networks:
      - backend


volumes:
  mongo_data:
  redis_data:
  frontend_dist:
    name: gatekeeper_frontend_dist

networks:
  backend: